CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(200)                            NOT NULL,
    email VARCHAR(200)                            NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS locations
(
    id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat float                                   NOT NULL,
    lon float                                   NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(200)                            NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation            VARCHAR(1000)                           NOT NULL,
    category_id           BIGINT                                  NOT NULL,
    confirmed_requests    BIGINT                                  NOT NULL,
    created_on            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    description           VARCHAR(3000)                           NOT NULL,
    event_date            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    initiator_id          BIGINT                                  NOT NULL,
    location_id           BIGINT                                  NOT NULL,
    is_paid               BOOLEAN                                 NOT NULL,
    participant_limit     BIGINT,
    published_on          TIMESTAMP WITHOUT TIME ZONE,
    is_request_moderation BOOLEAN,
    state                 VARCHAR(50)                             NOT NULL,
    title                 VARCHAR(200)                            NOT NULL,
    views                 BIGINT                                  NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (location_id) REFERENCES locations (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS compilations
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_pinned BOOLEAN,
    title     varchar(200)                            NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uq_compilation_title UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    FOREIGN KEY (compilation_id) REFERENCES compilations (id) ON DELETE CASCADE,
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    status       VARCHAR(200)                            NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    FOREIGN KEY (requester_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FRIENDSHIP
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id   BIGINT                                  NOT NULL,
    friend_id BIGINT                                  NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, friend_id)
);