CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app       VARCHAR(200)                            NOT NULL,
    uri       VARCHAR(200)                            NOT NULL,
    ip        VARCHAR(200)                            NOT NULL,
    timestamp TIMESTAMP                               NOT NULL,
    hits      BIGINT,
    CONSTRAINT pk_stat PRIMARY KEY (id)
);